name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Ermöglicht den manuellen Start
    inputs:
      version_name:
        description: 'Versionsnummer (v1.0.5)'
        required: true
        default: 'v1.0.0'
      is_prerelease:
        description: 'Pre-Release?'
        type: boolean
        default: false
      
jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    permissions:
      contents: write
    
    env:
      Solution_Name: Rmount.slnx
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: msbuild $env:Solution_Name /t:Rebuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Archive Files
      id: zip
      shell: pwsh
      run: |
        # Definition der Pfade (relativ zum Root des Repos)
          $exePath = "src/Rmount/bin/Release/net48/Rmount.exe"
          $iniPath = "docs/Rmount.ini.example"
          $zipName = "${{ github.workspace }}/Rmount-Release-${{ github.ref_name }}.zip"

          # Prüfen, ob die Dateien existieren (optionaler Safety-Check)
          if ((Test-Path $exePath) -and (Test-Path $iniPath)) {
              Compress-Archive -Path $exePath, $iniPath -DestinationPath $zipName -Force
              echo "ZIP erfolgreich erstellt: $zipName"
              echo "zip_path=$zipName" >> $env:GITHUB_OUTPUT
          } else {
              Write-Error "Eine der Dateien wurde nicht gefunden!"
              exit 1
          }
          echo "zip_path=$zipName" >> $env:GITHUB_OUTPUT
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.zip.outputs.zip_path }}
        body: "Release for ${{ github.ref_name }}"
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
